language: node_js
node_js:
  - "8"

cache:
  directories:
    - data

script:
  - npm run lint
  - npm run build

before_deploy:
  - ./scripts/beforeDeploy.sh

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build
  on:
    branch: master
