import { EIA_API } from './eiaApi';
import { IEA_API } from './ieaApi';
import { WORLD_BANK_API } from './worldBankApi';

// eslint-disable-next-line camelcase
import { convert_TWh_to_Mtoe, generationToConsumption } from './converters';

const statistics = [
  {
    code: 'COAL_PRODUCTION_MTOE',
    name: 'Coal production',
    description: '',
    startingYear: 1980,
    endingYear: 2016, // TODO
    unit: 'Mtoe',
    baseUnit: 'toe',
    unitFactor: 10 ** 6,
    sources: 'EIA, U.S. Energy Information Administration',
    api: EIA_API,
    seriesOfCountry: country => `INTL.7-1-${country.alpha3Code}-MTOE.A`,
    unitConverter: value => Number(value.toFixed(2)),
  },
  {
    code: 'COAL_CONSUMPTION_MTOE',
    name: 'Coal consumption',
    description: '',
    startingYear: 1980,
    endingYear: 2016, // TODO
    unit: 'Mtoe',
    baseUnit: 'toe',
    unitFactor: 10 ** 6,
    sources: 'EIA, U.S. Energy Information Administration',
    api: EIA_API,
    seriesOfCountry: country => `INTL.7-2-${country.alpha3Code}-MTOE.A`,
    unitConverter: value => Number(value.toFixed(2)),
  },
  {
    code: 'GAS_PRODUCTION_MTOE',
    name: 'Gas production',
    description: '',
    startingYear: 1980,
    endingYear: 2017,
    unit: 'Mtoe',
    baseUnit: 'toe',
    unitFactor: 10 ** 6,
    sources: 'EIA, U.S. Energy Information Administration',
    api: EIA_API,
    seriesOfCountry: country => `INTL.26-1-${country.alpha3Code}-MTOE.A`,
    unitConverter: value => Number(value.toFixed(2)),
  },
  {
    code: 'GAS_CONSUMPTION_MTOE',
    name: 'Gas consumption',
    description: '',
    startingYear: 1980,
    endingYear: 2017,
    unit: 'Mtoe',
    baseUnit: 'toe',
    unitFactor: 10 ** 6,
    sources: 'EIA, U.S. Energy Information Administration',
    api: EIA_API,
    seriesOfCountry: country => `INTL.26-2-${country.alpha3Code}-MTOE.A`,
    unitConverter: value => Number(value.toFixed(2)),
  },
  {
    code: 'OIL_PRODUCTION_MTOE',
    name: 'Oil production',
    description: '',
    startingYear: 1973,
    endingYear: 2014,
    unit: 'Mtoe',
    baseUnit: 'toe',
    unitFactor: 10 ** 6,
    sources: 'IEA',
    api: IEA_API,
    ieaId: '-21319742',
  },
  {
    code: 'OIL_CONSUMPTION_MTOE',
    name: 'Oil consumption',
    description: '',
    startingYear: 1973,
    endingYear: 2014,
    unit: 'Mtoe',
    baseUnit: 'toe',
    unitFactor: 10 ** 6,
    sources: 'IEA',
    api: IEA_API,
    ieaId: '642753284',
  },
  {
    code: 'HYDRO_CONSUMPTION_MTOE',
    name: 'Hydroelectricity consumption',
    description: '',
    startingYear: 1980,
    endingYear: 2016,
    unit: 'Mtoe',
    baseUnit: 'toe',
    unitFactor: 10 ** 6,
    sources: 'EIA, U.S. Energy Information Administration',
    api: EIA_API,
    seriesOfCountry: country => `INTL.33-12-${country.alpha3Code}-BKWH.A`,
    unitConverter: value =>
      Number(generationToConsumption(convert_TWh_to_Mtoe(value)).toFixed(2)),
  },
  {
    code: 'NUCLEAR_CONSUMPTION_MTOE',
    name: 'Nuclear consumption',
    description: '',
    startingYear: 1980,
    endingYear: 2016,
    unit: 'Mtoe',
    baseUnit: 'toe',
    unitFactor: 10 ** 6,
    sources: 'EIA, U.S. Energy Information Administration',
    api: EIA_API,
    seriesOfCountry: country => `INTL.27-12-${country.alpha3Code}-BKWH.A`,
    unitConverter: value =>
      Number(generationToConsumption(convert_TWh_to_Mtoe(value)).toFixed(2)),
  },
  {
    code: 'NON_HYDRO_RENEWABLES_CONSUMPTION_MTOE',
    name: 'Non-Hydroelectric renewables consumption',
    description: '',
    startingYear: 1980,
    endingYear: 2016,
    unit: 'Mtoe',
    baseUnit: 'toe',
    unitFactor: 10 ** 6,
    sources: 'EIA, U.S. Energy Information Administration',
    api: EIA_API,
    seriesOfCountry: country => `INTL.34-12-${country.alpha3Code}-BKWH.A`,
    unitConverter: value =>
      Number(generationToConsumption(convert_TWh_to_Mtoe(value)).toFixed(2)),
  },
  {
    code: 'WASTE_BIOMASS_CONSUMPTION_MTOE',
    name: 'Waste and biomass consumption',
    description: '',
    startingYear: 1980,
    endingYear: 2016,
    unit: 'Mtoe',
    baseUnit: 'toe',
    unitFactor: 10 ** 6,
    sources: 'EIA, U.S. Energy Information Administration',
    api: EIA_API,
    seriesOfCountry: country => `INTL.38-12-${country.alpha3Code}-BKWH.A`,
    unitConverter: value =>
      Number(generationToConsumption(convert_TWh_to_Mtoe(value)).toFixed(2)),
  },
  {
    code: 'PRIMARY_ENERGY_MTOE',
    name: 'Primary energy consumption',
    description: '',
    startingYear: 1980,
    endingYear: 2013,
    unit: 'Mtoe',
    baseUnit: 'toe',
    unitFactor: 10 ** 6,
    sources: 'EIA, U.S. Energy Information Administration',
    api: EIA_API,
    seriesOfCountry: country => `INTL.44-2-${country.alpha3Code}-MTOE.A`,
    unitConverter: value => Number(value.toFixed(2)),
  },
  {
    code: 'POPULATION',
    name: 'Population',
    description: '',
    startingYear: 1960,
    endingYear: 2017,
    unit: 'capita',
    sources: 'World Bank',
    api: WORLD_BANK_API,
    worldBankCode: 'SP.POP.TOTL',
  },
  {
    code: 'GDP_2010_USD',
    name: 'Gross Domestic Product',
    description: '',
    startingYear: 1960,
    endingYear: 2017,
    unit: 'million 2010 USD',
    baseUnit: '2010 $',
    unitFactor: 10 ** 6,
    sources: 'World Bank',
    api: WORLD_BANK_API,
    worldBankCode: 'NY.GDP.MKTP.KD',
    unitConverter: value => Number((value / 10 ** 6).toFixed(2)),
  },
  {
    code: 'CO2_EMISSIONS_GT',
    name: 'CO2 Emissions',
    description: '',
    startingYear: 1960,
    endingYear: 2014,
    unit: 'Mtonnes',
    baseUnit: 'tonnes',
    unitFactor: 10 ** 6,
    sources: 'World Bank',
    api: WORLD_BANK_API,
    worldBankCode: 'EN.ATM.CO2E.KT',
    unitConverter: value => Number((value / 10 ** 3).toFixed(2)),
  },
];

export default statistics;
